@echo Building GLFW Application...
g++ -c -I. -Iinclude src/main.cpp src/glad.c src/window.cpp src/VAO.cpp src/VBO.cpp src/EBO.cpp src/shaderClass.cpp src/Camera.cpp src/texture.cpp src/map.cpp
@echo Compilation complete, proceeding to linking...
g++ -o app.exe main.o glad.o window.o VAO.o VBO.o EBO.o shaderClass.o Camera.o texture.o map.o -L. -lglfw3 -lopengl32 -lgdi32 -lm
@echo Linking complete, running application...
.\app